esphome:
  friendly_name: Living Norte
  name: living-norte
  project:
    name: arivelli.nodemcu-32s_v1
    version: 1.0.0
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: living-norte
    password: 30EAgUDOl3Yk
captive_portal: null
logger:
  level: VERBOSE
api:
  encryption:
    key: MmAl3Emuz/G3P5fFO2gdmCAQjq4fULY5a4fEOUMC8Jg=
ota:
  platform: esphome
  password: qazwsx
binary_sensor:
  - platform: gpio
    id: living_norte_3_0__llave_luz_pool
    name: Llave luz pool
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        if:
          condition:
            and:
              - light.is_on: living_norte_1_0__luz_pool_1
              - light.is_on: living_norte_1_1__luz_pool_2
          then:
            - light.turn_off: living_norte_1_0__luz_pool_1
            - light.turn_off: living_norte_1_1__luz_pool_2
          else:
            if:
              condition:
                and:
                  - light.is_on: living_norte_1_0__luz_pool_1
              then:
                - light.turn_off: living_norte_1_0__luz_pool_1
                - light.turn_on: living_norte_1_1__luz_pool_2
              else:
                if:
                  condition:
                    and:
                      - light.is_on: living_norte_1_1__luz_pool_2
                  then:
                    - light.turn_on: living_norte_1_0__luz_pool_1
                    - light.turn_on: living_norte_1_1__luz_pool_2
                  else:
                    - light.turn_on: living_norte_1_0__luz_pool_1
  - platform: gpio
    id: living_norte_3_1__llave_luz_cocina
    name: Llave luz cocina
    pin:
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        - light.toggle: living_norte_1_3__luz_cocina
  - platform: gpio
    id: living_norte_3_2__llave_luz_ventilador
    name: Llave luz ventilador
    pin:
      number: GPIO33
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        - light.toggle: living_norte_1_2__luz_ventilador
  - platform: gpio
    id: living_norte_4_0__llave_luz_galera_viga
    name: Llave luz galería vigía
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        - light.toggle: living_norte_2_0__luz_galera_viga
  - platform: gpio
    id: living_norte_4_1__llave_luz_pasillo
    name: Llave luz pasillo
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        - light.toggle: living_norte_2_1__luz_pasillo
  - platform: gpio
    id: living_norte_4_2__llave_luz_entrada_principal
    name: Llave luz entrada principal
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        - light.toggle: living_norte_2_2__luz_entrada_principal
  - platform: gpio
    id: living_norte_4_3__llave_luz_guardarropas
    name: Llave luz guardarropas
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_state:
      then:
        - light.toggle: living_norte_2_3__luz_guardarropas
  - platform: gpio
    name: Llave garganta
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
light:
  - platform: binary
    name: Luz pool 1
    output: __living_norte_1_0__luz_pool_1
    id: living_norte_1_0__luz_pool_1
  - platform: binary
    name: Luz pool 2
    output: __living_norte_1_1__luz_pool_2
    id: living_norte_1_1__luz_pool_2
  - platform: binary
    name: Luz ventilador
    output: __living_norte_1_2__luz_ventilador
    id: living_norte_1_2__luz_ventilador
  - platform: binary
    name: Luz cocina
    output: __living_norte_1_3__luz_cocina
    id: living_norte_1_3__luz_cocina
  - platform: binary
    name: Luz galería vigía
    output: __living_norte_2_0__luz_galera_viga
    id: living_norte_2_0__luz_galera_viga
  - platform: binary
    name: Luz pasillo
    output: __living_norte_2_1__luz_pasillo
    id: living_norte_2_1__luz_pasillo
  - platform: binary
    name: luz entrada principal
    output: __living_norte_2_2__luz_entrada_principal
    id: living_norte_2_2__luz_entrada_principal
  - platform: binary
    name: Luz guardarropas
    output: __living_norte_2_3__luz_guardarropas
    id: living_norte_2_3__luz_guardarropas
  - platform: binary
    name: Luz entrada principal
    output: __living_norte_aux_0__luz_entrada_principal
    id: living_norte_aux_0__luz_entrada_principal
output:
  - platform: gpio
    pin: GPIO23
    id: __living_norte_1_0__luz_pool_1
    inverted: true
  - platform: gpio
    pin: GPIO19
    id: __living_norte_1_1__luz_pool_2
    inverted: true
  - platform: gpio
    pin: GPIO22
    id: __living_norte_1_2__luz_ventilador
    inverted: true
  - platform: gpio
    pin: GPIO21
    id: __living_norte_1_3__luz_cocina
    inverted: true
  - platform: gpio
    pin: GPIO18
    id: __living_norte_2_0__luz_galera_viga
    inverted: true
  - platform: gpio
    pin: GPIO04
    id: __living_norte_2_1__luz_pasillo
    inverted: true
  - platform: gpio
    pin: GPIO17
    id: __living_norte_2_2__luz_entrada_principal
    inverted: true
  - platform: gpio
    pin: GPIO16
    id: __living_norte_2_3__luz_guardarropas
    inverted: true
  - platform: gpio
    pin: GPIO00
    id: __living_norte_aux_0__luz_entrada_principal
    inverted: true
  - platform: gpio
    pin: GPIO02
    id: __living_norte_aux_1__portn_garage
    inverted: true
switch:
  - platform: output
    name: Portón garage
    output: __living_norte_aux_1__portn_garage
    id: living_norte_aux_1__portn_garage
    on_turn_on:
      then:
        - delay: 500ms
        - switch.turn_off: living_norte_aux_1__portn_garage
cover:
  - platform: template
    name: Portón garage
    open_action:
      - switch.turn_on: living_norte_aux_1__portn_garage
    close_action:
      - switch.turn_on: living_norte_aux_1__portn_garage
    stop_action:
      - switch.turn_on: living_norte_aux_1__portn_garage
    optimistic: true
    assumed_state: true
    icon: mdi:garage
