esphome:
  friendly_name: Living Sur
  name: living-sur2
  project:
    name: arivelli.nodemcu-32s_v1
    version: 1.0.0
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: living_sur
    password: 30EAgUDOl3Yk
captive_portal: null
logger:
  level: VERBOSE
api:
  encryption:
    key: MmAl3Emuz/G3P5fFO2gdmCAQjq4fULY5a4fEOUMC8Jg=
ota:
  platform: esphome
  password: qazwsx
binary_sensor:
  - platform: gpio
    id: living_sur_1_2__llave_persiana_living_subir
    name: Llave persiana living subir
    pin:
      number: GPIO22
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - if:
            condition:
              or:
                - switch.is_on: living_sur_1_0__persiana_living_subir
                - switch.is_on: living_sur_1_1__persiana_living_bajar
            then:
              - cover.stop: living_sur_persiana_living
            else:
              - cover.open: living_sur_persiana_living
  - platform: gpio
    id: living_sur_1_3__llave_persiana_living_bajar
    name: Llave persiana living bajar
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - if:
            condition:
              or:
                - switch.is_on: living_sur_1_0__persiana_living_subir
                - switch.is_on: living_sur_1_1__persiana_living_bajar
            then:
              - cover.stop: living_sur_persiana_living
            else:
              - cover.close: living_sur_persiana_living
  - platform: gpio
    id: living_sur_2_2__llave_de_luz_alacena
    name: Llave de luz alacena
    pin:
      number: GPIO17
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - light.toggle: living_sur_2_0__luz_alacena
  - platform: gpio
    id: living_sur_3_2__llave_de_luz_galera_lamparitas
    name: Llave de luz galería lamparitas
    pin:
      number: GPIO33
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - light.toggle: living_sur_3_0__luz_galera_lamparitas
  - platform: gpio
    id: living_sur_3_3__llave_de_luz_parrillero
    name: Llave de luz parrillero
    pin:
      number: GPIO25
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - light.toggle: living_sur_3_1__luz_parrillero
  - platform: gpio
    id: living_sur_4_2__llave_persiana_juegos_subir
    name: Llave persiana juegos subir
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - if:
            condition:
              or:
                - switch.is_on: living_sur_4_0__persiana_juegos_subir
                - switch.is_on: living_sur_4_1__persiana_juegos_bajar
            then:
              - cover.stop: living_sur_persiana_juegos
            else:
              - cover.open: living_sur_persiana_juegos
  - platform: gpio
    id: living_sur_4_3__llave_persiana_juegos_bajar
    name: Llave persiana juegos bajar
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
    on_press:
      then:
        - if:
            condition:
              or:
                - switch.is_on: living_sur_4_0__persiana_juegos_subir
                - switch.is_on: living_sur_4_1__persiana_juegos_bajar
            then:
              - cover.stop: living_sur_persiana_juegos
            else:
              - cover.close: living_sur_persiana_juegos
  - platform: gpio
    name: Llave garganta
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
light:
  - platform: binary
    name: Luz alacena
    output: __living_sur_2_0__luz_alacena
    id: living_sur_2_0__luz_alacena
  - platform: binary
    name: Luz galería lamparitas
    output: __living_sur_3_0__luz_galera_lamparitas
    id: living_sur_3_0__luz_galera_lamparitas
  - platform: binary
    name: Luz parrillero
    output: __living_sur_3_1__luz_parrillero
    id: living_sur_3_1__luz_parrillero
output:
  - platform: gpio
    pin: GPIO23
    id: __living_sur_1_0__persiana_living_subir
    inverted: true
  - platform: gpio
    pin: GPIO19
    id: __living_sur_1_1__persiana_living_bajar
    inverted: true
  - platform: gpio
    pin: GPIO18
    id: __living_sur_2_0__luz_alacena
    inverted: true
  - platform: gpio
    pin: GPIO32
    id: __living_sur_3_0__luz_galera_lamparitas
    inverted: true
  - platform: gpio
    pin: GPIO26
    id: __living_sur_3_1__luz_parrillero
    inverted: true
  - platform: gpio
    pin: GPIO27
    id: __living_sur_4_0__persiana_juegos_subir
    inverted: true
  - platform: gpio
    pin: GPIO13
    id: __living_sur_4_1__persiana_juegos_bajar
    inverted: true
switch:
  - platform: output
    name: Persiana living subir
    output: __living_sur_1_0__persiana_living_subir
    id: living_sur_1_0__persiana_living_subir
  - platform: output
    name: Persiana living bajar
    output: __living_sur_1_1__persiana_living_bajar
    id: living_sur_1_1__persiana_living_bajar
  - platform: output
    name: Persiana juegos subir
    output: __living_sur_4_0__persiana_juegos_subir
    id: living_sur_4_0__persiana_juegos_subir
  - platform: output
    name: Persiana juegos bajar
    output: __living_sur_4_1__persiana_juegos_bajar
    id: living_sur_4_1__persiana_juegos_bajar
cover:
  - platform: time_based
    id: living_sur_persiana_living
    name: Persiana Living
    device_class: curtain
    open_action:
      - switch.turn_on: living_sur_1_0__persiana_living_subir
    open_duration: 180sec
    close_action:
      - switch.turn_on: living_sur_1_1__persiana_living_bajar
    close_duration: 180sec
    stop_action:
      - switch.turn_off: living_sur_1_0__persiana_living_subir
      - switch.turn_off: living_sur_1_1__persiana_living_bajar
  - platform: time_based
    id: living_sur_persiana_juegos
    name: Persiana Sala de juegos
    device_class: curtain
    open_action:
      - switch.turn_on: living_sur_4_0__persiana_juegos_subir
    open_duration: 108sec
    close_action:
      - switch.turn_on: living_sur_4_1__persiana_juegos_bajar
    close_duration: 108sec
    stop_action:
      - switch.turn_off: living_sur_4_0__persiana_juegos_subir
      - switch.turn_off: living_sur_4_1__persiana_juegos_bajar
