esphome:
  friendly_name: Living
  name: living
  project:
    name: arivelli.nodemcu-32s_v1
    version: 1.0.0
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: living
    password: 30EAgUDOl3Yk
captive_portal: null
logger:
  level: VERY_VERBOSE
api:
  encryption:
    key: MmAl3Emuz/G3P5fFO2gdmCAQjq4fULY5a4fEOUMC8Jg=
ota:
  password: qazwsx
binary_sensor:
  - platform: gpio
    id: living_4_0_llave_de_luz_parrilla
    name: Llave de luz parrilla
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_4_1_llave_de_luz_galera_lamparitas
    name: Llave de luz galería lamparitas
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_4_2_llave_de_luz_cocina
    name: Llave de luz cocina
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_4_3_llave_de_luz_bajo_alacena
    name: Llave de luz bajo alacena
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_in_0_llave_luz_cocina
    name: Llave luz cocina
    pin:
      number: GPIO34
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_in_1_llave_luz_galera_viga
    name: Llave luz galería vigía
    pin:
      number: GPIO35
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_in_2_llave_subir_persiana_living
    name: Llave subir persiana living
    pin:
      number: GPIO36
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_in_3_llave_bajar_persiana_living
    name: Llave bajar persiana living
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_aux_0_llave_de_luz_pool
    name: Llave de luz pool
    pin:
      number: GPIO00
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_aux_1_llave_de_luz_ventilador
    name: Llave de luz ventilador
    pin:
      number: GPIO02
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    id: living_aux_2_llave_de_luz_garganta
    name: Llave de luz garganta
    pin:
      number: GPIO05
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
  - platform: gpio
    name: Llave garganta
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms
light:
  - platform: binary
    name: Luces pool 1
    output: __living_1_0_luces_pool_1
    id: living_1_0_luces_pool_1
  - platform: binary
    name: Luces pool 2
    output: __living_1_1_luces_pool_2
    id: living_1_1_luces_pool_2
  - platform: binary
    name: Luces ventilador
    output: __light_ventilador
    id: light_ventilador
  - platform: binary
    name: Luz cocina
    output: __living_1_3_luz_cocina
    id: living_1_3_luz_cocina
  - platform: binary
    name: Luz galería vigía
    output: __living_2_0_luz_galera_viga
    id: living_2_0_luz_galera_viga
  - platform: binary
    name: Luz galería lamparitas
    output: __living_2_1_luz_galera_lamparitas
    id: living_2_1_luz_galera_lamparitas
  - platform: binary
    name: Luz parrillero
    output: __living_2_2_luz_parrillero
    id: living_2_2_luz_parrillero
  - platform: binary
    name: Luz bajo alacena
    output: __living_2_3_luz_bajo_alacena
    id: living_2_3_luz_bajo_alacena
  - platform: binary
    name: Luz pasillo
    output: __living_3_0_luz_pasillo
    id: living_3_0_luz_pasillo
  - platform: binary
    name: Luz cocina
    output: __living_3_1_luz_cocina
    id: living_3_1_luz_cocina
output:
  - platform: gpio
    pin: GPIO23
    id: __living_1_0_luces_pool_1
  - platform: gpio
    pin: GPIO19
    id: __living_1_1_luces_pool_2
  - platform: gpio
    pin: GPIO22
    id: __light_ventilador
  - platform: gpio
    pin: GPIO21
    id: __living_1_3_luz_cocina
  - platform: gpio
    pin: GPIO18
    id: __living_2_0_luz_galera_viga
  - platform: gpio
    pin: GPIO04
    id: __living_2_1_luz_galera_lamparitas
  - platform: gpio
    pin: GPIO17
    id: __living_2_2_luz_parrillero
  - platform: gpio
    pin: GPIO16
    id: __living_2_3_luz_bajo_alacena
  - platform: gpio
    pin: GPIO32
    id: __living_3_0_luz_pasillo
  - platform: gpio
    pin: GPIO26
    id: __living_3_1_luz_cocina
  - platform: gpio
    pin: GPIO33
    id: __living_3_2_subir_persiana_living
  - platform: gpio
    pin: GPIO25
    id: __living_3_3_bajar_persiana_living
switch:
  - platform: output
    name: Subir persiana living
    output: __living_3_2_subir_persiana_living
    id: living_3_2_subir_persiana_living
  - platform: output
    name: Bajar persiana living
    output: __living_3_3_bajar_persiana_living
    id: living_3_3_bajar_persiana_living
