
import 'tailwindcss/tailwind.css'

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'


import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
const icons = [
  faBan,
  faBars,
  faBell,
  faBinoculars,
  faBookReader,
  faBriefcase,
  faCalendar, faCalendarAlt, faCalendarCheck, faCalendarDay, faCalendarMinus, faCalendarPlus, faCalendarTimes, faCalendarWeek,
  faCheck,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChartBar,
  faCheckCircle,
  faCircleInfo,
  faCity,
  faClipboardCheck,
  faClock,
  faCogs,
  faCommentMedical,
  faDollarSign,
  faDownload,
  faEraser,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faFile, faFileAlt, faFileCircleCheck, faFileCode, faFileInvoiceDollar, faFileExcel, faFilePen, faFileSignature, faFileWaveform,
  faFloppyDisk,
  faFolder, faFolderOpen,
  faHandPointRight,
  faIdCard,
  faKey,
  faPencilAlt,
  faPercent,
  faPlus,
  faRightFromBracket,
  faRotate,
  faRuler,
  faSignInAlt,
  faSitemap,
  faSort,
  faSortDown,
  faSortUp,
  faTasks,
  faTh,
  faTimes,
  faTrash,
  faTrashRestore,
  faUser,
  faUserGear,
  faUpload,
  faCircleUser
];
import {
  faBan,
  faBars,
  faBell,
  faBinoculars,
  faBookReader,
  faBriefcase,
  faCalendar, faCalendarAlt, faCalendarCheck, faCalendarDay, faCalendarMinus, faCalendarPlus, faCalendarTimes, faCalendarWeek,
  faCheck,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChartBar,
  faCheckCircle,
  faCircleInfo,
  faCity,
  faClipboardCheck,
  faClock,
  faCogs,
  faCommentMedical,
  faDollarSign,
  faDownload,
  faEraser,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faFile, faFileAlt, faFileCircleCheck, faFileCode, faFileInvoiceDollar, faFileExcel, faFilePen, faFileSignature, faFileWaveform,
  faFloppyDisk,
  faFolder, faFolderOpen,
  faHandPointRight,
  faIdCard,
  faKey,
  faPencilAlt,
  faPercent,
  faPlus,
  faRightFromBracket,
  faRotate,
  faRuler,
  faSignInAlt,
  faSitemap,
  faSort,
  faSortDown,
  faSortUp,
  faTasks,
  faTh,
  faTimes,
  faTrash,
  faTrashRestore,
  faUser,
  faUserGear,
  faUpload,
  faCircleUser,
} from "@fortawesome/free-solid-svg-icons";

library.add(icons);

const app = createApp(App)

app.use(router)
  .component('font-awesome-icon', FontAwesomeIcon)
  .mount('#app');
